/* NOVA OS Pro Enhancements: extra games, wallpaper studio and personalization. */
(function(){
  const extraGames=[['guess','🎲','Sayı Tahmini'],['rps','✊','Taş Kağıt Makas'],['whack','🎯','Hedef Vurma'],['color','🎨','Renk Hafızası']];
  const appInfo=[['wallpaper','🖼️','Arka Plan','Resim veya çiziminizi kullanın'],['about','ℹ️','NOVA Hakkında','Sistem bilgileri']];
  const $=s=>document.querySelector(s);
  const open=k=>{if(typeof window.openApp==='function')window.openApp(k);else window.dispatchEvent(new CustomEvent('nova:open',{detail:k}))};
  function toast(t){if(typeof window.toast==='function')window.toast(t,'✦');}
  function saveWallpaper(url){localStorage.setItem('novaWallpaper',url);document.body.style.setProperty('--nova-wallpaper',`url("${url}")`);const d=$('#desktop');if(d)d.style.backgroundImage=`linear-gradient(135deg,rgba(5,8,20,.38),rgba(5,8,20,.18)),url("${url}")`;toast('Arka plan uygulandı');}
  function wallpaper(el){el.innerHTML='<div class="hero"><h1>Arka Plan Stüdyosu</h1><p class="muted">Hazır görsel seçin, cihazınızdan resim yükleyin veya Paint çiziminizi kullanın.</p></div><div class="wallpaper-presets"><button data-wall="#111827">Gece</button><button data-wall="#152e4a">Okyanus</button><button data-wall="#321b4c">Mor Galaksi</button><button data-wall="#203b2b">Orman</button></div><div class="toolbar"><label class="action">Resim yükle <input id="wall-file" type="file" accept="image/*" hidden></label><button class="action" id="use-paint">Paint çizimini kullan</button><button id="clear-wall">Varsayılana dön</button></div><p class="muted">Yüklenen görseller tarayıcınızda saklanır.</p>';el.querySelectorAll('[data-wall]').forEach(b=>b.onclick=()=>{const c=b.dataset.wall;localStorage.removeItem('novaWallpaper');document.body.style.setProperty('--nova-wallpaper','none');const d=$('#desktop');d.style.backgroundImage='';d.style.backgroundColor=c;toast('Renkli arka plan uygulandı')});el.querySelector('#wall-file').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>saveWallpaper(r.result);r.readAsDataURL(f)};el.querySelector('#use-paint').onclick=()=>{const p=localStorage.getItem('novaPaint');if(p)saveWallpaper(p);else toast('Önce Paint ile bir çizim kaydedin')};el.querySelector('#clear-wall').onclick=()=>{localStorage.removeItem('novaWallpaper');document.body.style.backgroundImage='';const d=$('#desktop');d.style.backgroundImage='';d.style.backgroundColor='';toast('Arka plan sıfırlandı')}}
  function about(el){el.innerHTML='<div class="hero"><h1>NOVA OS</h1><p class="muted">Tarayıcıda çalışan kişisel Web OS deneyimi.</p></div><div class="list"><div class="list-row">Sürüm <b>2.1 Pro</b></div><div class="list-row">Depolama <b>Yerel tarayıcı</b></div><div class="list-row">Durum <b>Hazır ✓</b></div></div>'}
  function extraGame(id,el){el.innerHTML='<div class="game-layout"><div class="game-head"><span class="muted">Skor</span><span class="score">0</span></div><div class="game-mount"></div></div>';const m=el.querySelector('.game-mount'),s=el.querySelector('.score');if(id==='guess'){let n=Math.floor(Math.random()*20)+1,tries=0;m.innerHTML='<p>1 ile 20 arasında bir sayı tuttum.</p><input type="number" min="1" max="20" placeholder="Tahminin"><button class="action">Dene</button><p class="muted"></p>';const i=m.querySelector('input'),b=m.querySelector('button'),h=m.querySelector('p:last-child');b.onclick=()=>{tries++;const v=+i.value;if(v===n){s.textContent=Math.max(1,21-tries);h.textContent='Tebrikler! Yeni oyun için tekrar açın.';b.disabled=true}else h.textContent=v<n?'Daha büyük bir sayı deneyin.':'Daha küçük bir sayı deneyin.'}}else if(id==='rps'){m.innerHTML='<p>Seçimini yap:</p><div class="cards">'+['✊','✋','✌️'].map(x=>`<button class="card" data-choice="${x}">${x}</button>`).join('')+'</div><p class="muted"></p>';m.onclick=e=>{const b=e.target.closest('[data-choice]');if(!b)return;const choices=['✊','✋','✌️'],cpu=choices[Math.floor(Math.random()*3)],user=b.dataset.choice;const win=(user==='✊'&&cpu==='✌️')||(user==='✋'&&cpu==='✊')||(user==='✌️'&&cpu==='✋');s.textContent=win?1:0;m.querySelector('.muted').textContent=`Bilgisayar: ${cpu} · ${user===cpu?'Berabere':win?'Kazandın!':'Tekrar dene'}`}}else if(id==='whack'){let n=0;m.innerHTML='<button class="action target">🎯</button><p class="muted">Hedefe hızlıca tıkla!</p>';const b=m.querySelector('button');b.onclick=()=>{n++;s.textContent=n;b.style.transform=`translate(${Math.random()*120-60}px,${Math.random()*100-50}px)`}}else{let colors=['🔴','🔵','🟢','🟡'],seq=[],input=[];m.innerHTML='<p class="sequence">Hazır ol…</p><div class="cards">'+colors.map(c=>`<button class="card" data-c="${c}">${c}</button>`).join('')+'</div>';const show=()=>{seq.push(colors[Math.floor(Math.random()*4)]);m.querySelector('.sequence').textContent=seq.join(' ');setTimeout(()=>m.querySelector('.sequence').textContent='Şimdi tekrar et!',700)};m.onclick=e=>{const b=e.target.closest('[data-c]');if(!b)return;input.push(b.dataset.c);if(input[input.length-1]!==seq[input.length-1]){m.querySelector('.sequence').textContent='Yanlış! Baştan başla.';seq=[];input=[];return}if(input.length===seq.length){s.textContent=seq.length;input=[];setTimeout(show,450)}};show()}}
  function install(){const oldRender=window.render;window.render=function(k,e){if(k==='wallpaper')return wallpaper(e);if(k==='about')return about(e);if(extraGames.some(g=>g[0]===k))return extraGame(k,e);return oldRender?oldRender(k,e):undefined};
    const desktop=$('#desktop-icons'),list=$('#app-list');if(!desktop||!list)return;
    const add=(root,a,cls='desktop-icon')=>{const b=document.createElement('button');b.className=cls;b.dataset.open=a[0];b.innerHTML=cls==='desktop-icon'?`<span class="icon">${a[1]}</span><small>${a[2]}</small>`:`<span>${a[1]}</span><div><b>${a[2]}</b><small>${a[3]||'Uygulama'}</small></div>`;root.append(b)};
    appInfo.forEach(a=>add(desktop,a));extraGames.forEach(a=>add(list,[...a,'Mini oyun'],'app-item'));
    appInfo.forEach(a=>add(list,a,'app-item'));
    const oldWall=localStorage.getItem('novaWallpaper');if(oldWall)saveWallpaper(oldWall);
    if(!document.body.dataset.proEvents){document.body.dataset.proEvents='1';desktop.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b)open(b.dataset.open)});list.addEventListener('click',e=>{const b=e.target.closest('[data-open]');if(b){open(b.dataset.open);$('#start-menu')?.classList.add('hidden')}})}
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,0));else setTimeout(install,0);
})();
