/* NOVA OS: stable window manager and lightweight apps */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const apps=[['arcade','🎮','Oyun Merkezi','Tüm oyunlar'],['files','📁','Dosyalar','Kişisel alan'],['notes','📝','Not Defteri','Yazı yaz'],['calc','🧮','Hesap Makinesi','Hızlı hesap'],['terminal','⌘','Terminal','Komut satırı'],['paint','🎨','Paint Studio','Çizim yap'],['settings','⚙️','Ayarlar','Kişiselleştir'],['scores','🏆','Skorlar','Rekorlar']];
const games=[['clicker','⚡','Enerji Tıklayıcı'],['tictactoe','❌','SOS / Tic-Tac-Toe'],['memory','🃏','Hafıza Kartları'],['2048','🔢','2048'],['typing','⌨️','Hızlı Yaz'],['reaction','🎯','Tepki Testi']];
const all=[...apps,...games.map(x=>[x[0],x[1],x[2], 'Mini oyun'])];let windows=new Map(),z=10,muted=false;
function tone(freq=440){if(muted)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=tone.ctx||(tone.ctx=new C()),o=c.createOscillator(),g=c.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.12);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.12)}catch(e){}}
function toast(msg,icon='✦'){const t=document.createElement('div');t.className='toast glass';t.innerHTML=`<b>${icon}</b><span>${msg}</span>`;$('#toasts').append(t);setTimeout(()=>t.remove(),2600)}
function focus(w){z++;w.style.zIndex=z;$$('.task').forEach(x=>x.classList.toggle('active',x.dataset.key===w.dataset.key))}
function tasks(){const e=$('#task-items');e.innerHTML='';windows.forEach((w,key)=>{const b=document.createElement('button');b.className='task';b.dataset.key=key;b.textContent=w.dataset.title;b.onclick=()=>{w.classList.remove('min');focus(w)};e.append(b)})}
function openApp(key,title=all.find(a=>a[0]===key)?.[2]||key){if(windows.has(key)){const w=windows.get(key);w.classList.remove('min');focus(w);return}const data=all.find(a=>a[0]===key)||['', '▣',title];const w=document.createElement('article');w.className='window glass';w.dataset.key=key;w.dataset.title=title;w.style.left=`${Math.max(18,Math.min(innerWidth-740,120+windows.size*24))}px`;w.style.top=`${Math.max(18,Math.min(innerHeight-620,70+windows.size*20))}px`;w.innerHTML=`<header class="window-bar"><div class="window-title"><span>${data[1]}</span>${title}</div><div class="window-actions"><button data-act="min" title="Küçült">—</button><button data-act="close" title="Kapat">×</button></div></header><div class="window-body"></div>`;$('#windows').append(w);windows.set(key,w);drag(w);render(key,w.querySelector('.window-body'));focus(w);tasks();tone(620)}
function close(w){w.remove();windows.delete(w.dataset.key);tasks();tone(180)}
function drag(w){w.onpointerdown=()=>focus(w);const bar=w.querySelector('.window-bar');bar.onpointerdown=e=>{if(e.target.closest('button')||innerWidth<701)return;const r=w.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top;bar.setPointerCapture(e.pointerId);bar.onpointermove=ev=>{w.style.left=Math.max(5,Math.min(innerWidth-w.offsetWidth-5,ev.clientX-sx))+'px';w.style.top=Math.max(5,Math.min(innerHeight-w.offsetHeight-80,ev.clientY-sy))+'px'};bar.onpointerup=()=>bar.onpointermove=null};w.querySelector('[data-act=close]').onclick=()=>close(w);w.querySelector('[data-act=min]').onclick=()=>{w.classList.add('min');tasks()}}
function render(key,el){if(key==='arcade')return arcade(el);if(key==='notes')return notes(el);if(key==='calc')return calculator(el);if(key==='terminal')return terminal(el);if(key==='paint')return paint(el);if(key==='files')return files(el);if(key==='settings')return settings(el);if(key==='scores')return scores(el);return game(key,el)}
function arcade(el){el.innerHTML=`<div class="hero"><h1>Oyun Merkezi</h1><p class="muted">${games.length} stabil mini oyun — skorlarınız cihazınızda saklanır.</p></div><div class="cards">${games.map(g=>`<div class="card" data-game="${g[0]}"><span>${g[1]}</span><b>${g[2]}</b><small>Oyna →</small></div>`).join('')}</div>`;el.onclick=e=>{const c=e.target.closest('[data-game]');if(c)openApp(c.dataset.game,games.find(g=>g[0]===c.dataset.game)[2])}}
function notes(el){el.innerHTML='<div class="toolbar"><button class="action" id="save-note">Kaydet</button><span class="muted">Otomatik yerel kayıt açık</span></div><textarea class="note" placeholder="Notlarınızı buraya yazın…"></textarea>';const n=el.querySelector('textarea');n.value=localStorage.novaNote||'';const save=()=>{localStorage.novaNote=n.value;toast('Not kaydedildi','✓')};n.oninput=save;el.querySelector('#save-note').onclick=save}
function calculator(el){el.innerHTML='<div class="calc"><div class="calc-display">0</div><div class="calc-grid">'+['C','⌫','%','÷','7','8','9','×','4','5','6','−','1','2','3','+','0','.','±','='].map(x=>`<button>${x}</button>`).join('')+'</div></div>';let d=el.querySelector('.calc-display'),v='';el.onclick=e=>{if(!e.target.matches('button'))return;const x=e.target.textContent;if(x==='C')v='';else if(x==='⌫')v=v.slice(0,-1);else if(x==='='){try{v=String(Function('return '+v.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-'))())}catch{v='Hata'}}else if(x==='±')v=v.startsWith('-')?v.slice(1):'-'+v;else v+=x;d.textContent=v||'0'}}
function terminal(el){el.innerHTML='<div class="terminal"><div class="terminal-out">NOVA Terminal 2.0\nYardım için <b>help</b> yazın.\n\n</div><div>nova@webos:~$ <input autofocus autocomplete="off"></div></div>';const out=el.querySelector('.terminal-out'),i=el.querySelector('input');i.onkeydown=e=>{if(e.key!=='Enter')return;const c=i.value.trim();let r=c==='help'?'Komutlar: help, date, clear, about':c==='date'?new Date().toLocaleString('tr-TR'):c==='about'?'NOVA OS — tarayıcıda çalışan güvenli masaüstü':c==='clear'?'':`Komut bulunamadı: ${c}`;out.innerHTML+=`nova@webos:~$ ${c}\n${r}\n`;i.value='';el.scrollTop=el.scrollHeight}}
function files(el){el.innerHTML='<div class="hero"><h1>Dosyalar</h1><p class="muted">Kişisel alanınız · yerel depolama</p></div><div class="list"><div class="list-row">📁 Projeler <span class="muted">klasör</span></div><div class="list-row">📄 hoş-geldin.txt <span class="muted">1 KB</span></div><div class="list-row">🖼️ duvar-kağıdı.png <span class="muted">2.4 MB</span></div></div>'}
function scores(el){el.innerHTML='<h1>En Yüksek Skorlar</h1><p class="muted">Rekorlarınız bu cihazda tutulur.</p><div class="list">'+games.map(g=>`<div class="list-row">${g[1]} ${g[2]} <b>${localStorage['hs-'+g[0]]||0}</b></div>`).join('')+'</div>'}
function settings(el){el.innerHTML=`<div class="settings"><h1>Kişiselleştirme</h1><label>Vurgu rengi</label><input id="accent" type="color" value="${localStorage.accent||'#8b5cf6'}"><label><input id="reduce" type="checkbox"> Animasyonları azalt</label><p class="muted">Tema ve renk tercihleri otomatik kaydedilir.</p></div>`;el.querySelector('#accent').oninput=e=>{document.documentElement.style.setProperty('--accent',e.target.value);localStorage.accent=e.target.value};el.querySelector('#reduce').onchange=e=>document.body.classList.toggle('reduced',e.target.checked)}
function paint(el){el.innerHTML='<div class="toolbar"><input type="color" id="brush" value="#8b5cf6"><button class="action" id="clear-canvas">Temizle</button><button class="action" id="save-canvas">PNG kaydet</button></div><canvas class="paint-canvas" width="900" height="500"></canvas>';const c=el.querySelector('canvas'),x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);let down=false;x.lineWidth=5;x.lineCap='round';const pos=e=>{const r=c.getBoundingClientRect();return[(e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height]};c.onpointerdown=e=>{down=true;x.beginPath();x.moveTo(...pos(e))};c.onpointermove=e=>{if(down){x.strokeStyle=el.querySelector('#brush').value;x.lineTo(...pos(e));x.stroke()}};c.onpointerup=()=>down=false;el.querySelector('#clear-canvas').onclick=()=>{x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height)};el.querySelector('#save-canvas').onclick=()=>{const a=document.createElement('a');a.download='nova-cizim.png';a.href=c.toDataURL();a.click()}}
function game(id,el){el.innerHTML='<div class="game-layout"><div class="game-head"><span class="muted">Skor</span><span class="score">0</span></div><div class="game-mount"></div></div>';const m=el.querySelector('.game-mount'),s=el.querySelector('.score');if(id==='clicker')clicker(m,s);if(id==='tictactoe')ttt(m,s);if(id==='memory')memory(m,s);if(id==='2048')two048(m,s);if(id==='typing')typing(m,s);if(id==='reaction')reaction(m,s)}
function saveScore(id,n){const k='hs-'+id;if(n>+(localStorage[k]||0)){localStorage[k]=n;toast('Yeni rekor!','🏆')}}
function clicker(m,s){let n=0;m.innerHTML='<button class="action" style="font-size:70px;padding:35px">⚡</button><p class="muted">Enerji çekirdeğine tıkla!</p>';m.querySelector('button').onclick=()=>{s.textContent=++n;saveScore('clicker',n);tone(500)}}
function ttt(m,s){let b=Array(9).fill(''),turn='X',n=0;m.innerHTML='<div class="tic">'+b.map((_,i)=>`<button data-i="${i}"></button>`).join('')+'</div><p class="muted">Bilgisayara karşı oyna</p>';const win=a=>[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(q=>q.every(i=>a[i]));m.onclick=e=>{if(!e.target.dataset.i||b[e.target.dataset.i])return;let i=+e.target.dataset.i;b[i]=turn;e.target.textContent=turn;if(win(b)||b.every(Boolean)){if(win(b)){n+=10;s.textContent=n;saveScore('tictactoe',n);toast('Oyun bitti!','🎉')}return}turn='O';let free=b.map((x,i)=>x?null:i).filter(x=>x!==null);if(free.length){let j=free[Math.floor(Math.random()*free.length)];b[j]='O';m.querySelector(`[data-i="${j}"]`).textContent='O';turn='X'}}}
function memory(m,s){const vals=['🌙','🌙','☀️','☀️','🌊','🌊','🔥','🔥'].sort(()=>Math.random()-.5);let open=[],found=0;m.innerHTML='<div class="memory">'+vals.map((_,i)=>`<button data-i="${i}">?</button>`).join('')+'</div>';m.onclick=e=>{const b=e.target;if(!b.dataset.i||open.length===2||b.classList.contains('open'))return;const i=+b.dataset.i;b.textContent=vals[i];b.classList.add('open');open.push([i,b]);if(open.length===2){if(vals[open[0][0]]===vals[open[1][0]]){found++;open=[];s.textContent=found;saveScore('memory',found)}else setTimeout(()=>{open.forEach(x=>{x[1].textContent='?';x[1].classList.remove('open')});open=[]},650)}}}
function two048(m,s){let a=Array(16).fill(0);a[Math.floor(Math.random()*16)]=2;const paint=()=>{m.innerHTML='<div class="board2048">'+a.map(x=>`<button>${x||''}</button>`).join('')+'</div><p class="muted">Ok tuşları veya WASD ile hareket et</p>'};const move=e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','w','a','s','d'].includes(e.key))return;e.preventDefault();const d=(e.key==='ArrowRight'||e.key==='d')?1:(e.key==='ArrowLeft'||e.key==='a')?-1:0;let lines=[];for(let r=0;r<4;r++){let line=d?a.slice(r*4,r*4+4):[a[r],a[r+4],a[r+8],a[r+12]];if(d<0)line.reverse();line=line.filter(Boolean);for(let i=0;i<line.length-1;i++)if(line[i]===line[i+1]){line[i]*=2;line.splice(i+1,1);s.textContent=+s.textContent+line[i]};while(line.length<4)line.push(0);if(d<0)line.reverse();for(let i=0;i<4;i++)d?a[r*4+i]=line[i]:a[r+i*4]=line[i]}let free=a.map((x,i)=>x?null:i).filter(x=>x!==null);if(free.length)a[free[Math.floor(Math.random()*free.length)]]=2;paint()};paint();window.addEventListener('keydown',move);const old=windows.get([...windows.keys()].find(k=>windows.get(k)?.querySelector('.board2048')===m));if(old)old.querySelector('[data-act=close]').addEventListener('click',()=>window.removeEventListener('keydown',move))}
function typing(m,s){const text='NOVA OS ile geleceğin masaüstünü keşfet.';m.innerHTML=`<p>${text}</p><input placeholder="Metni yazmaya başla…" style="width:100%;padding:13px;background:rgba(255,255,255,.08);border:1px solid var(--line);border-radius:10px">`;let start;const i=m.querySelector('input');i.oninput=()=>{start??=Date.now();if(i.value===text){const n=Math.round(text.length/((Date.now()-start)/60000));s.textContent=n;saveScore('typing',n);toast('Harika!','⌨️')}}}
function reaction(m,s){m.innerHTML='<button class="action">Hazır olduğunda tıkla</button>';const b=m.querySelector('button');b.onclick=()=>{b.textContent='Bekle…';b.disabled=true;setTimeout(()=>{const t=Date.now();b.textContent='ŞİMDİ TIKLA!';b.disabled=false;b.onclick=()=>{const n=Date.now()-t;s.textContent=n+' ms';saveScore('reaction',Math.max(1,1000-n));b.textContent='Tekrar dene'}},800+Math.random()*1800)}}
function renderIcons(){const e=$('#desktop-icons');e.innerHTML=apps.map(a=>`<button class="desktop-icon" data-open="${a[0]}"><span class="icon">${a[1]}</span><small>${a[2]}</small></button>`).join('')}
function renderApps(filter=''){const e=$('#app-list');e.innerHTML=all.filter(a=>a[2].toLocaleLowerCase('tr').includes(filter.toLocaleLowerCase('tr'))).map(a=>`<button class="app-item" data-open="${a[0]}"><span>${a[1]}</span><div><b>${a[2]}</b><small>${a[3]}</small></div></button>`).join('')}
function init(){renderIcons();renderApps();$('#desktop-icons').onclick=e=>{const b=e.target.closest('[data-open]');if(b)openApp(b.dataset.open)};$('#app-list').onclick=e=>{const b=e.target.closest('[data-open]');if(b){openApp(b.dataset.open);$('#start-menu').classList.add('hidden')}};$('#start-button').onclick=()=>{$('#start-menu').classList.toggle('hidden');$('#start-button').setAttribute('aria-expanded',!$('#start-menu').classList.contains('hidden'));if(!$('#start-menu').classList.contains('hidden'))$('#app-search').focus()};$('#app-search').oninput=e=>renderApps(e.target.value);$('#theme-toggle').onclick=()=>{document.body.classList.toggle('light');localStorage.light=document.body.classList.contains('light');toast('Tema değiştirildi','☾')};$('#mute').onclick=e=>{muted=!muted;e.target.textContent=muted?'🔇':'🔊'};$('#clock').textContent='';setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'}),1000);if(localStorage.light==='true')document.body.classList.add('light');if(localStorage.accent)document.documentElement.style.setProperty('--accent',localStorage.accent)}
init();
