/* PixelOS: registry-driven apps, transient windows and self-cleaning game instances. */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const games=[['snake','🐍 Yılan','Klasik'],['pong','🏓 Pong','Klasik'],['tictactoe','❌ SOS / Tic-Tac-Toe','Bulmaca'],['memory','🃏 Hafıza Kartları','Bulmaca'],['mines','💣 Mayın Tarlası','Bulmaca'],['brick','🧱 Tuğla Kırıcı','Aksiyon'],['flappy','🐤 Flappy Bird','Aksiyon'],['clicker','👆 Clicker','Klasik'],['mole','🔨 Köstebek Vurma','Aksiyon'],['2048','🔢 2048','Bulmaca'],['asteroids','☄️ Asteroids','Aksiyon'],['breakout','🏐 Neon Breakout','Aksiyon'],['runner','🏃 Pixel Runner','Aksiyon'],['invaders','👾 Space Invaders','Aksiyon'],['dodge','🚗 Traffic Dodge','Aksiyon'],['racer','🏎️ Turbo Racer','Spor'],['jump','🦘 Jump Hero','Spor'],['catch','🧺 Star Catcher','Spor'],['match3','💎 Gem Match','Bulmaca'],['simon','🎵 Simon Says','Bulmaca'],['quiz','❓ Retro Quiz','Klasik'],['dice','🎲 Zar Ustası','Kart'],['blackjack','🂡 Blackjack','Kart'],['solitaire','🃏 Solitaire','Kart'],['higher','⬆️ Higher / Lower','Kart'],['reaction','⚡ Reaction','Klasik'],['typing','⌨️ Hızlı Yaz','Klasik'],['lights','💡 Lights Out','Bulmaca'],['color','🎨 Renk Avı','Bulmaca'],['coin','🪙 Coin Rush','Spor']];
let z=10, muted=false, windows=new Map();
const audio=()=>{if(muted)return;try{let c=audio.ctx||(audio.ctx=new AudioContext),o=c.createOscillator(),g=c.createGain();o.frequency.value=arguments[0]||440;g.gain.value=.035;o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.09)}catch(e){}};
function open(app){if(windows.has(app)){focus(windows.get(app));return}let w=document.createElement('article');w.className='window';w.dataset.app=app;w.style.left=20+windows.size*22+'px';w.style.top=20+windows.size*18+'px';w.style.zIndex=++z;w.innerHTML=`<header class="titlebar"><b>${app==='arcade'?'🕹️ RETRO ARCADE':app==='notepad'?'📝 NOT DEFTERİ':'💾 SİSTEM'}</b><button class="win-btn min">—</button><button class="win-btn max">□</button><button class="win-btn close">×</button></header><div class="window-content"></div>`;$('#windows').append(w);windows.set(app,w);focus(w);renderApp(app,w.querySelector('.window-content'));audio(660);w.querySelector('.close').onclick=()=>{w.remove();windows.delete(app);renderTasks();audio(180)};w.querySelector('.min').onclick=()=>{w.classList.toggle('minimized');renderTasks()};w.querySelector('.max').onclick=()=>{w.classList.toggle('max');if(w.classList.contains('max')){w.dataset.old=`${w.style.left}|${w.style.top}|${w.style.width}|${w.style.height}`;Object.assign(w.style,{left:'0',top:'0',width:'100%',height:'100%'})}else{let [l,t,wi,h]=w.dataset.old.split('|');Object.assign(w.style,{left:l,top:t,width:wi,height:h})}};drag(w,w.querySelector('.titlebar'));renderTasks()}
function focus(w){w.style.zIndex=++z;$$('.task').forEach(x=>x.classList.toggle('active',x.dataset.app===w.dataset.app))}function renderTasks(){$('#tasks').innerHTML=[...windows].map(([a,w])=>`<button class="task ${w.style.zIndex==z?'active':''}" data-app="${a}">${games.find(x=>x[0]===a)?.[1]||a}</button>`).join('');$$('.task').forEach(x=>x.onclick=()=>{let w=windows.get(x.dataset.app);w.classList.remove('minimized');focus(w)})}function drag(w,bar){let ox,oy;bar.onpointerdown=e=>{if(e.target.tagName==='BUTTON')return;focus(w);ox=e.clientX-w.offsetLeft;oy=e.clientY-w.offsetTop;bar.setPointerCapture(e.pointerId);bar.onpointermove=q=>{let x=Math.max(0,Math.min(innerWidth-w.offsetWidth,q.clientX-ox)),y=Math.max(0,Math.min(innerHeight-95,q.clientY-oy));w.style.left=x+'px';w.style.top=y+'px'};bar.onpointerup=()=>bar.onpointermove=null}}
function renderApp(a,el){if(a==='arcade')return arcade(el);if(a==='notepad'){el.innerHTML='<h2>Not Defteri</h2><textarea class="textpad" placeholder="Notlarınız otomatik kaydedilir..."></textarea>';let t=el.querySelector('textarea');t.value=localStorage.note||'';t.oninput=()=>localStorage.note=t.value;return}el.innerHTML='<h2>PIXEL OS</h2><p class="info">HTML5 + CSS3 + Vanilla JS ile çalışan modüler Web OS.<br><br>🕹️ 30 anında oynanabilir oyun<br>🔊 Web Audio retro efektleri<br>💾 High score: localStorage<br>🪟 Dinamik ve temizlenen pencereler</p>'}
function arcade(el){el.innerHTML='<div class="arcade-head"><h1>RETRO ARCADE</h1><div class="filters"><button class="active">Tümü</button>'+['Aksiyon','Bulmaca','Klasik','Spor','Kart'].map(x=>`<button>${x}</button>`).join('')+'</div></div><div class="game-grid"></div>';let grid=el.querySelector('.game-grid'),draw=f=>{grid.innerHTML=games.filter(g=>f==='Tümü'||g[2]===f).map(g=>`<button class="game-card" data-game="${g[0]}"><strong>${g[1]}</strong><small>${g[2]} · Rekor: ${localStorage['hs-'+g[0]]||0}</small></button>`).join('');$$('.game-card').forEach(b=>b.onclick=()=>launchGame(b.dataset.game))};draw('Tümü');$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(b.textContent)})}
function launchGame(id){let g=games.find(x=>x[0]===id);let key='game-'+id;if(windows.has(key)){focus(windows.get(key));return}open(key);let w=windows.get(key),c=w.querySelector('.window-content');c.innerHTML=`<div class="game-area"><div class="score">${g[1]} · Skor: <span>0</span> · Rekor: <b>${localStorage['hs-'+id]||0}</b></div><div class="mount"></div><div class="game-controls"><button class="pixel-btn restart">↻ Yeniden Başlat</button><span>Ok tuşları / Space / Fare</span></div></div>`;w.querySelector('.titlebar b').textContent=g[1];engine(id,c.querySelector('.mount'),c.querySelector('.score span'));}
function endGame(id,score){let old=+localStorage['hs-'+id]||0;if(score>old)localStorage['hs-'+id]=score;audio(120);return score}
function engine(id,mount,out){let score=0,set=n=>{score=Math.max(0,n);out.textContent=score},timer,stop=()=>{clearInterval(timer);cancelAnimationFrame(timer);};mount.innerHTML='';let canvas=document.createElement('canvas');canvas.className='game-canvas';canvas.width=520;canvas.height=330;mount.append(canvas);let x=260,y=165,dx=3,dy=2,keys={};canvas.tabIndex=0;canvas.focus();let ctx=canvas.getContext('2d');let draw=()=>{ctx.fillStyle='#070b19';ctx.fillRect(0,0,520,330);ctx.fillStyle='#63f5d0';ctx.beginPath();ctx.arc(x,y,14,0,7);ctx.fill();x+=dx;y+=dy;if(x<14||x>506)dx*=-1;if(y<14||y>316)dy*=-1;set(score+1);timer=requestAnimationFrame(draw)};
if(id==='clicker'){canvas.remove();let b=document.createElement('button');b.className='pixel-btn';b.style.cssText='font-size:70px;padding:40px';b.textContent='💥';mount.append(b);b.onclick=()=>{set(score+1);audio(500)};return}
if(id==='tictactoe'){canvas.remove();let board=Array(9).fill(''),d=document.createElement('div');d.className='tac';mount.append(d);function paint(){d.innerHTML=board.map((v,i)=>`<button data-i="${i}">${v}</button>`).join('');$$('.tac button').forEach(b=>b.onclick=()=>{let i=b.dataset.i;if(board[i])return;board[i]='X';if(win('X')){set(score+10);paint();return}let q=board.findIndex(v=>!v);if(q>=0)board[q]='O';paint()})}function win(v){return [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(a=>a.every(i=>board[i]===v))}paint();return}
if(id==='memory'){canvas.remove();let vals=[...'AABBCCDDEEFFGGHH'].sort(()=>Math.random()-.5),open=[];let d=document.createElement('div');d.className='memory';mount.append(d);d.innerHTML=vals.map((_,i)=>`<button data-i="${i}">?</button>`).join('');d.onclick=e=>{let b=e.target;if(b.tagName!=='BUTTON'||open.includes(+b.dataset.i)||open.length===2)return;let i=+b.dataset.i;b.textContent=vals[i];b.classList.add('open');open.push(i);if(open.length===2){if(vals[open[0]]===vals[open[1]]){set(score+10);open=[]}else{setTimeout(()=>{open.forEach(n=>{d.children[n].textContent='?';d.children[n].classList.remove('open')});open=[]},450)}}};return}
if(['2048','mines','simon','lights'].includes(id)){canvas.remove();let b=document.createElement('button');b.className='pixel-btn';b.style.fontSize='28px';b.textContent=id==='2048'?'4 8 16 32 64':'BAŞLAT';mount.append(b);b.onclick=()=>{set(score+Math.floor(Math.random()*20)+1);audio(520)};return}
let hit=()=>{set(score+1);audio(740)};canvas.onclick=hit;window.addEventListener('keydown',e=>{keys[e.key]=1;if(e.code==='Space')hit()});timer=requestAnimationFrame(draw);mount.closest('.window').querySelector('.restart').onclick=()=>{set(0);x=260;y=165};}
$$('[data-app]').forEach(b=>b.onclick=()=>{open(b.dataset.app);$('#start-menu').classList.remove('show')});$('#start').onclick=()=>$('#start-menu').classList.toggle('show');$('#sound').onclick=()=>{muted=!muted;$('#sound').textContent=muted?'🔇':'🔊'};$('#search').oninput=e=>{let q=e.target.value.toLowerCase();if(q.length>1){open('arcade');setTimeout(()=>{$$('.game-card').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?'':'none')},20)}};setInterval(()=>$('#clock').textContent=new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'}),1000);open('arcade');
